<script lang="ts">
	import { onMount } from 'svelte';
	import { authStore } from '$lib/auth/auth-store.svelte';
	import { createUrn, deleteUrn, listSpirits, listUrnHistory, listUrns, updateUrn, type Spirit, type Urn, type UrnHistory, type UrnInput } from '$lib/memorial/api';
	import { uploadUrnImage } from '$lib/uploads/api';
	import { houseFilter } from '$lib/memorial/house-filter.svelte';
	import LoadingIndicator from '$lib/ui/LoadingIndicator.svelte';
	import Popup from '$lib/ui/Popup.svelte';
	import { popupStore } from '$lib/ui/popup-store.svelte';
	import { toastStore } from '$lib/ui/toast-store.svelte';

	const empty = (): UrnInput => ({ spirit_id: '', code: '', urn_type: '', material: '', color: '', dimensions: '', storage_location: '', installed_at: '', moved_at: '', image_url: '', status: 'installed', notes: '' });
	const statusLabel = (status: Urn['status']) => status === 'installed' ? 'Đã lắp' : status === 'moved' ? 'Đã di dời' : 'Đã hoàn trả';
	let items = $state<Urn[]>([]); let spirits = $state<Spirit[]>([]); let form = $state<UrnInput>(empty()); let editing = $state<Urn | null>(null);
	let history = $state<UrnHistory[]>([]); let historyUrn = $state<Urn | null>(null); let open = $state(false); let historyOpen = $state(false); let pickerOpen = $state(false); let pickerQuery = $state(''); let q = $state(''); let loading = $state(true); let saving = $state(false); let imageUploading = $state(false); let spiritsLoading = $state(false); let spiritsRequest: Promise<void> | null = null;
	let canManage = $derived(authStore.can('memorial.manage'));
	let shown = $derived(items.filter((item) => item.house_id === houseFilter.id && `${item.full_name} ${item.code} ${item.storage_location}`.toLowerCase().includes(q.toLowerCase())));
	let selectedSpirit = $derived(spirits.find((spirit) => spirit.id === form.spirit_id));
	let pickable = $derived(spirits.filter((spirit) => spirit.house_id === houseFilter.id && (!spirit.has_urn || spirit.id === form.spirit_id) && `${spirit.full_name} ${spirit.dharma_name} ${spirit.position_name} ${spirit.tablet_name}`.toLowerCase().includes(pickerQuery.toLowerCase())));
	onMount(() => { void load(); void ensureSpirits(); const onHouseSelect = () => { spirits = []; void load(); void ensureSpirits(); }; window.addEventListener('memorial-house-select', onHouseSelect); return () => window.removeEventListener('memorial-house-select', onHouseSelect); });
	async function load() { loading = true; try { items = await listUrns(); } catch (error) { toastStore.error(error instanceof Error ? error.message : 'Không tải được Hũ cốt'); } finally { loading = false; } }
	async function ensureSpirits() { if (spirits.length || !houseFilter.id) return; if (spiritsRequest) return spiritsRequest; spiritsLoading = true; const houseID = houseFilter.id; spiritsRequest = listSpirits('', houseID, '', 500, 0).then((page) => { if (houseFilter.id === houseID) spirits = page.spirits; }).catch((error) => { toastStore.error(error instanceof Error ? error.message : 'Không tải được Hương linh'); }).finally(() => { spiritsLoading = false; spiritsRequest = null; }); return spiritsRequest; }
	function add() { editing = null; form = empty(); open = true; void ensureSpirits(); }
	function chooseSpirit(spirit: Spirit) { form.spirit_id = spirit.id; pickerOpen = false; }
	function edit(item: Urn) { editing = item; form = { spirit_id: item.spirit_id, code: item.code, urn_type: item.urn_type, material: item.material, color: item.color, dimensions: item.dimensions, storage_location: item.storage_location, installed_at: item.installed_at, moved_at: item.moved_at, image_url: item.image_url, status: item.status, notes: item.notes }; open = true; void ensureSpirits(); }
	async function selectImage(file: File) { imageUploading = true; try { form.image_url = await uploadUrnImage(file); toastStore.success('Đã tải ảnh Hũ cốt'); } catch (error) { toastStore.error(error instanceof Error ? error.message : 'Không thể tải ảnh'); } finally { imageUploading = false; } }
	async function save() { if (!editing && !form.spirit_id) { toastStore.error('Chọn Hương linh'); return; } saving = true; try { editing ? await updateUrn(editing.id, form) : await createUrn(form); toastStore.success('Đã lưu Hũ cốt'); open = false; await load(); } catch (error) { toastStore.error(error instanceof Error ? error.message : 'Không thể lưu'); } finally { saving = false; } }
	async function remove(item: Urn) { if (!await popupStore.confirm({ title: 'Xóa Hũ cốt?', message: `Xóa thông tin của ${item.full_name}?`, confirmLabel: 'Xóa', cancelLabel: 'Hủy', tone: 'danger' })) return; try { await deleteUrn(item.id); toastStore.success('Đã xóa Hũ cốt'); await load(); } catch (error) { toastStore.error(error instanceof Error ? error.message : 'Không thể xóa'); } }
	async function showHistory(item: Urn) { historyUrn = item; history = []; historyOpen = true; try { history = await listUrnHistory(item.id); } catch (error) { toastStore.error(error instanceof Error ? error.message : 'Không tải được lịch sử'); } }
</script>

<section class="h-full overflow-auto p-4 md:p-6"><div class="mx-auto max-w-7xl">
	<div class="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-xl font-semibold text-[var(--color-text)]">Quản lý Hũ cốt</h1><p class="mt-1 text-sm text-[var(--color-text-secondary)]">Thông tin, vị trí, ảnh và lịch sử thay đổi Hũ cốt.</p></div><div class="flex flex-wrap gap-2"><input bind:value={q} class="h-10 rounded-md border border-[var(--color-border-strong)] bg-[var(--color-surface)] px-3 text-sm outline-none focus:border-[var(--color-primary)]" placeholder="Tìm mã hũ, Hương linh..." />{#if canManage}<button onclick={() => void add()} class="h-10 rounded-md bg-[var(--color-primary)] px-4 text-sm font-semibold text-white hover:bg-[var(--color-primary-dark)]">+ Thêm Hũ cốt</button>{/if}</div></div>
	{#if loading}<LoadingIndicator label="Đang tải Hũ cốt..." />{:else}<div class="overflow-x-auto rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)]"><table class="w-full min-w-300 text-left text-sm"><thead class="bg-[var(--color-surface-muted)] text-xs text-[var(--color-text-secondary)]"><tr><th class="px-4 py-3 font-semibold">Mã hũ</th><th class="px-4 py-3 font-semibold">Ảnh</th><th class="px-4 py-3 font-semibold">Họ tên</th><th class="px-4 py-3 font-semibold">Pháp danh</th><th class="px-4 py-3 font-semibold">Năm sinh</th><th class="px-4 py-3 font-semibold">Năm mất</th><th class="px-4 py-3 font-semibold">Loại</th><th class="px-4 py-3 font-semibold">Vị trí lưu</th><th class="px-4 py-3 font-semibold">Ngày di dời</th><th class="px-4 py-3 font-semibold">Trạng thái</th><th class="px-4 py-3 text-right font-semibold">Thao tác</th></tr></thead><tbody class="divide-y divide-[var(--color-border)]">{#each shown as item (item.id)}<tr class="transition-colors hover:bg-[var(--color-primary-soft)]/40"><td class="px-4 py-3">{item.code || '—'}</td><td class="px-4 py-3">{#if item.image_url}<img src={item.image_url} alt={`Hũ cốt ${item.code}`} class="h-10 w-10 rounded object-cover" />{:else}<span class="grid h-10 w-10 place-items-center rounded border text-[var(--color-text-muted)]">—</span>{/if}</td><td class="px-4 py-3 font-medium">{item.full_name}</td><td class="px-4 py-3">{item.dharma_name || '—'}</td><td class="px-4 py-3">{item.birth_year || '—'}</td><td class="px-4 py-3">{item.death_year || '—'}</td><td class="px-4 py-3">{item.urn_type || '—'}</td><td class="px-4 py-3">{item.storage_location || '—'}</td><td class="px-4 py-3">{item.moved_at || '—'}</td><td class="px-4 py-3"><span class="rounded-full bg-[var(--color-surface-muted)] px-2 py-1 text-xs font-medium">{statusLabel(item.status)}</span></td><td class="px-4 py-3 text-right"><button onclick={() => void showHistory(item)} class="mr-3 text-xs font-semibold text-[var(--color-primary-dark)]">Lịch sử</button>{#if canManage}<button onclick={() => void edit(item)} class="mr-3 text-xs font-semibold text-[var(--color-primary-dark)]">Sửa</button><button onclick={() => void remove(item)} class="text-xs font-semibold text-[var(--color-danger)]">Xóa</button>{/if}</td></tr>{/each}</tbody></table></div>{/if}
</div></section>

<Popup {open} title={editing ? 'Cập nhật Hũ cốt' : 'Thêm Hũ cốt'} sizeClass="max-w-2xl" onClose={() => !saving && (open = false)}><form onsubmit={(event) => { event.preventDefault(); void save(); }} class="grid gap-3 md:grid-cols-2">
	<label class="md:col-span-2">Hương linh *<button type="button" onclick={() => pickerOpen = true} class="mt-1 flex h-10 w-full items-center justify-between rounded border px-3 text-left">{selectedSpirit ? `${selectedSpirit.full_name}${selectedSpirit.position_name ? ` — ${selectedSpirit.position_name}` : ''}` : 'Chọn Hương linh'}<span>⌄</span></button></label>
	{#if selectedSpirit}<div class="md:col-span-2 rounded-md border border-[var(--color-border)] bg-[var(--color-surface-muted)]/45 p-3"><p class="text-xs font-semibold uppercase tracking-wide text-[var(--color-text-secondary)]">Thông tin Hương linh liên kết</p><div class="mt-2 grid gap-2 text-sm sm:grid-cols-2"><p><span class="text-[var(--color-text-secondary)]">Pháp danh:</span> {selectedSpirit.dharma_name || '—'}</p><p><span class="text-[var(--color-text-secondary)]">Năm sinh – mất:</span> {selectedSpirit.birth_year || '—'} – {selectedSpirit.death_year || '—'}</p><p><span class="text-[var(--color-text-secondary)]">Bài vị:</span> {selectedSpirit.tablet_name || 'Chưa xếp'}</p><p><span class="text-[var(--color-text-secondary)]">Vị trí:</span> {selectedSpirit.position_name || 'Chưa xếp'}</p></div></div>{/if}
	<label>Mã hũ<input bind:value={form.code} class="mt-1 h-10 w-full rounded border px-3" /></label><label>Loại hũ<input bind:value={form.urn_type} class="mt-1 h-10 w-full rounded border px-3" /></label><label>Chất liệu<input bind:value={form.material} class="mt-1 h-10 w-full rounded border px-3" /></label><label>Màu sắc<input bind:value={form.color} class="mt-1 h-10 w-full rounded border px-3" /></label><label>Kích thước<input bind:value={form.dimensions} class="mt-1 h-10 w-full rounded border px-3" /></label><label>Vị trí lưu<input bind:value={form.storage_location} class="mt-1 h-10 w-full rounded border px-3" /></label><label>Ngày lắp<input type="date" bind:value={form.installed_at} class="mt-1 h-10 w-full rounded border px-3" /></label><label>Ngày di dời<input type="date" bind:value={form.moved_at} class="mt-1 h-10 w-full rounded border px-3" /></label><label>Trạng thái<select bind:value={form.status} class="mt-1 h-10 w-full rounded border px-3"><option value="installed">Đã lắp</option><option value="moved">Đã di dời</option><option value="returned">Đã hoàn trả</option></select></label><label>Ảnh Hũ cốt<input type="file" accept="image/*" disabled={imageUploading} onchange={(event) => { const file = event.currentTarget.files?.[0]; if (file) void selectImage(file); }} class="mt-1 block w-full text-sm" />{#if form.image_url}<a class="mt-1 block text-sm text-[var(--color-primary-dark)]" href={form.image_url} target="_blank" rel="noreferrer">Xem ảnh đã tải</a>{/if}</label><label class="md:col-span-2">Ghi chú<textarea bind:value={form.notes} class="mt-1 min-h-20 w-full rounded border p-3"></textarea></label><div class="flex justify-end gap-3 md:col-span-2"><button type="button" onclick={() => open = false} class="h-10 rounded border px-4">Hủy</button><button disabled={saving || imageUploading} class="h-10 rounded bg-[var(--color-primary)] px-4 text-white">{saving ? 'Đang lưu...' : imageUploading ? 'Đang tải ảnh...' : 'Lưu'}</button></div>
</form></Popup>
<Popup open={historyOpen} title={`Lịch sử Hũ cốt${historyUrn?.code ? ` · ${historyUrn.code}` : ''}`} sizeClass="max-w-xl" onClose={() => historyOpen = false}>{#if history.length === 0}<p class="text-sm text-[var(--color-text-secondary)]">Chưa có lịch sử thay đổi.</p>{:else}<div class="space-y-3">{#each history as item (item.id)}<div class="rounded border p-3"><div class="flex justify-between gap-3"><strong>{statusLabel(item.status as Urn['status'])}</strong><span class="text-sm text-[var(--color-text-secondary)]">{item.changed_at}</span></div><p class="mt-1 text-sm">Vị trí: {item.storage_location || '—'}</p><p class="mt-1 text-sm text-[var(--color-text-secondary)]">{item.notes || 'Cập nhật Hũ cốt'}</p></div>{/each}</div>{/if}</Popup>
<Popup open={pickerOpen} title="Chọn Hương linh" sizeClass="max-w-4xl" layerClass="z-50" onClose={() => pickerOpen = false}><input bind:value={pickerQuery} class="h-10 w-full rounded border px-3" placeholder="Tìm tên, pháp danh, vị trí hoặc Bài vị..." /><div class="mt-3 max-h-100 overflow-auto rounded border"><table class="w-full text-left text-sm"><thead><tr><th class="p-2">Hương linh</th><th class="p-2">Pháp danh</th><th class="p-2">Vị trí</th><th class="p-2">Bài vị</th><th class="p-2 text-right">Thao tác</th></tr></thead><tbody>{#each pickable as spirit (spirit.id)}<tr class="border-t hover:bg-[var(--color-surface-muted)]"><td class="p-2 font-medium">{spirit.full_name}</td><td class="p-2">{spirit.dharma_name || '—'}</td><td class="p-2">{spirit.position_name || '—'}</td><td class="p-2">{spirit.tablet_name || '—'}</td><td class="p-2 text-right"><button type="button" onclick={() => chooseSpirit(spirit)} class="h-8 rounded bg-[var(--color-primary)] px-3 text-xs font-semibold text-white">Chọn</button></td></tr>{/each}</tbody></table></div></Popup>
